### ISSUE TITLE
Make a game moderator tab

### ISSUE THREAD

**Issue by Oipo** [IdleLands/DesktopFE#4]
This would probably also mean an API change in IdleLands core, to query if the user is a moderator or not.

Basically, mirror the current IRC commands like
- [idle-teleport](http://doks.idle.land/#!/Client/IRC%20Commands/idle-teleport)
- [idle-ban](http://doks.idle.land/#!/Client/IRC%20Commands/idle-ban)
- [idle-unban](http://doks.idle.land/#!/Client/IRC%20Commands/idle-unban)

**Comment by seiyria** [comment]
This is actually not possible with the current API. The only "gm commands" that I have are "approve content" and "destroy content" -- it looks like this:

![](http://puu.sh/eUNDx/d5a7d7f0f9.png)

But then again, that's only for content moderators. GMs will not get externally available commands, they will have to use the Remote Debug Shell (when it's created).

**Comment by Oipo** [comment]
Okay, not possible then
